export const formFields = [
  {
    name: 'company',
    label: 'Company',
    type: 'text',
    value: 'company',
    placeholder: 'Company providing the opportunity',
  },
  {
    name: 'title',
    label: 'Title',
    type: 'text',
    value: 'title',
    placeholder: 'Concise title of the opportunity',
  },
  {
    name: 'job_description',
    label: 'Job Description',
    type: 'textarea',
    value: 'job_description',
    placeholder: 'Describe about the opportunity',
  },
  {
    name: 'category',
    label: 'Category',
    type: 'text',
    value: 'category',
    placeholder: 'Category of the opportunity',
  },
  {
    name: 'opportunity_type',
    label: 'Opportunity type',
    type: 'text',
    value: 'oppor_type',
    placeholder: 'Type of the opportunity',
  },
  {
    name: 'additional_info',
    label: 'Additional Information',
    type: 'text',
    value: 'add_info',
    placeholder: 'Additional information regarding the opportunity',
  },
  {
    name: 'location',
    label: 'Location',
    type: 'text',
    value: 'location',
    placeholder: 'Place of joining/Remote',
  },
  {
    name: 'ctc',
    label: 'CTC',
    type: 'number',
    value: 100,
    placeholder: 'CTC being offered',
  },
  {
    name: 'ctc_info',
    label: 'CTC Info',
    type: 'text',
    value: 'ctc_info',
    placeholder: 'Description of the CTC',
  },
  {
    name: 'allowed_branches',
    label: 'Allowed branches',
    type: 'text',
    value: 'allowed_branches',
    placeholder:
      'Mention the eligible branches in Block letters separated by a space',
  },
  {
    name: 'class_10_percentage_criteria',
    label: 'Class 10 or equivalent',
    type: 'number',
    value: 100,
    placeholder: 'X percentage',
  },
  {
    name: 'class_12_percentage_criteria',
    label: 'Class 12 or equivalent',
    type: 'number',
    value: 100,
    placeholder: 'XII percentage',
  },
  {
    name: 'cgpa',
    label: 'CGPA',
    type: 'number',
    value: 10,
  }, // No matching placeholder
  {
    name: 'allowed_genders',
    label: 'Allowed genders',
    type: 'text',
    value: 'allowed_genders',
    placeholder: 'Mention the eligible genders separated by a space',
  },
  {
    name: 'batch',
    label: 'Batch',
    type: 'text',
    value: '2025',
    placeholder: 'Batch(year) that is eligible',
  },
  {
    name: 'backlog',
    label: 'Backlogs',
    type: 'text',
    value: 'backlogs',
    placeholder: 'Number of backlogs allowed',
  },
  {
    name: 'registration_date',
    label: 'Registration Deadline',
    type: 'date',
    value: '2025-03-26',
    placeholder: 'Last date for registration',
  },
  {
    name: 'form_link',
    label: 'Form Link',
    type: 'url',
    value: 'https://www.forms.google.com',
    placeholder: 'URL of any external form',
  },
];
