export const fields = [
  { name: 'company', label: 'Company', type: 'text' },
  { name: 'title', label: 'Title', type: 'text' },
  { name: 'job_description', label: 'Job Description', type: 'textarea' },
  { name: 'opportunity_type', label: 'Opportunity type', type: 'text' },
  { name: 'additional_info', label: 'Additional Information', type: 'text' },
  { name: 'location', label: 'Location', type: 'text' },
  { name: 'ctc', label: 'CTC', type: 'number' },
  { name: 'ctc_info', label: 'CTC Info', type: 'text' },
  { name: 'allowed_branches', label: 'Allowed branches', type: 'text' },
  {
    name: 'class_10_percentage_criteria',
    label: 'Class 10 or equivalent',
    type: 'number',
  },
  {
    name: 'class_12_percentage_criteria',
    label: 'Class 12 or equivalent',
    type: 'number',
  },
  {
    name: 'cgpa',
    label: 'CGPA',
    type: 'number',
  },
  { name: 'allowed_genders', label: 'Allowed genders', type: 'text' },
  { name: 'batch', label: 'Batch', type: 'text' },
  { name: 'registration_date', label: 'Registration Deadline', type: 'date' },
  { name: 'form_link', label: 'Form Link', type: 'url' },
];
